export const PHOTOGRAPHY = {
  name: 'Photography',
  description: [''],
  photos: [
    { uri: '/photography/Arashiyama.jpg', title: 'Arashiyama, Kyoto, Japan' },
    { uri: '/photography/Bath.jpg', title: 'Bath, England' },
    { uri: '/photography/Belem.jpg', title: 'Belem, Portugal' },
    { uri: '/photography/Highland.jpeg', title: 'Cladish, Scotland' },
    { uri: '/photography/England.jpeg', title: 'Dorset, England' },
    { uri: '/photography/Edinburgh.jpg', title: 'Edinburgh, Scotland' },
    { uri: '/photography/Gold Bluffs.jpeg', title: 'Gold Bluffs, Redwood National Forest, California' },
    { uri: '/photography/Golden Gardens.jpeg', title: 'Golden Gardens Park, Seattle, Washington' },
    { uri: '/photography/Porto.jpeg', title: 'Igreja do Carmo, Porto, Portugal' },
    { uri: '/photography/Skye.jpg', title: 'Isle of Skye, Scotland' },
    { uri: '/photography/Kastellet.jpg', title: 'Kastellet, Copenhagen, Denmark' },
    { uri: '/photography/Oxford.jpg', title: 'Magdalen College, Oxford, England' },
    { uri: '/photography/Okinawa.jpg', title: 'Okinawa, Japan' },
    { uri: '/photography/Quirang.jpg', title: 'Quirang, Isle of Skye, Scotland' },
    { uri: '/photography/Kyoto.jpg', title: 'Sanjusangendo, Kyoto, Japan' },
    { uri: '/photography/Gum.jpeg', title: 'Seattle, Washington' },
    { uri: '/photography/St Joseph.jpeg', title: 'St Joseph, Michigan' },
    { uri: '/photography/Stonehenge.jpg', title: 'Stonehenge, England' },
    { uri: '/photography/Scotland.jpeg', title: 'Three Sisters, Glencoe, Scotland' },
    { uri: '/photography/Trolltunga.jpg', title: 'Trolltunga, Norway' },
    { uri: '/photography/Michigan.jpg', title: 'West Bloomfield, Michigan' },
  ],
  component: 'grid',
  styles: {
    groupHeight: 350,
  },
}